# Generated by Django 3.2.7 on 2021-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('GADGETS', 'GADGETS'), ('ELECTRONICS', 'ELECTRONICS'), ('AUTOMOBILE', 'AUTOMOBILE'), ('OFFICE SPACE', 'OFFICE SPACE'), ('AGRICULTURAL', 'AGRICULTURAL')], max_length=255),
        ),
    ]
