# Generated by Django 3.2.7 on 2021-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210918_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='payment_method',
            field=models.CharField(choices=[('AIRTIME TOPUP', 'AIRTIME TOPUP'), ('CASH TRANSFER', 'CASH TRANSFER')], default='AIRTIME TOPUP', max_length=255),
        ),
    ]
