# Generated by Django 3.2.7 on 2021-09-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
