# Generated by Django 3.2.7 on 2021-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.PositiveIntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(default='My Bank', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+2348012345678', max_length=50),
        ),
    ]
